excluded:
  - Pods
  - Carthage
disabled_rules:
  - line_length
  - trailing_whitespace
type_name:
  allowed_symbols: "_"
identifier_name:
  allowed_symbols: "_"
  min_length: # only min_length
    warning: 1
    error: 1
  max_length:
    warning: 60
    error: 80
force_cast: warning

cyclomatic_complexity:
  warning: 50
  error: 100
